# Generated by Django 2.0.3 on 2018-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField(default=0)),
                ('ust_name', models.CharField(max_length=200)),
            ],
        ),
    ]
