# Generated by Django 2.0.3 on 2018-06-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('choice', models.CharField(choices=[('B', 'bici'), ('P', 'piedi'), ('M', 'macchina'), ('L', 'mezzi pubblici'), ('X', 'macchina e mezzi pubblici')], default='L', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('when_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='habit',
            name='usr_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usertable.User'),
        ),
    ]
