# Generated by Django 2.0.3 on 2018-03-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hab_id', models.IntegerField(default=0)),
                ('hab_time', models.DateTimeField(verbose_name='date published')),
                ('hab_choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField(default=0)),
                ('usr_name', models.CharField(max_length=200)),
            ],
        ),
    ]
