# Generated by Django 2.0.3 on 2018-05-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertable', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habits',
            new_name='Habit',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
