# Generated by Django 2.0.3 on 2018-05-28 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usertable', '0002_auto_20180503_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usr_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usr_id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='when_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
