# Generated by Django 2.0.3 on 2018-05-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usertable', '0002_auto_20180503_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='hab_choice',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='hab_id',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='hab_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usr_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usr_name',
        ),
        migrations.AddField(
            model_name='habit',
            name='choice',
            field=models.CharField(choices=[('B', 'bici'), ('P', 'piedi'), ('M', 'macchina'), ('L', 'mezzi pubblici'), ('X', 'macchina e mezzi pubblici')], default='P', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='usr_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usertable.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='when_registered',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
