# Generated by Django 2.0.3 on 2018-05-28 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usertable', '0003_auto_20180528_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='choice',
            field=models.CharField(choices=[('B', 'bici'), ('P', 'piedi'), ('M', 'macchina'), ('L', 'mezzi pubblici'), ('X', 'macchina e mezzi pubblici')], default='L', max_length=200),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='habit',
            name='usr_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usertable.User'),
        ),
    ]
